// secrets.h - Wireless Credentials Template
#ifndef SECRETS_H
#define SECRETS_H


#define YOUR_SSID "PASTE_YOUR_SSID_HERE"
#define YOUR_PASS "PASTE_YOUR_PASSWORD_HERE"
#define YOUR_OTA_PASS "PASTE_YOUR_OTA_PASS_HERE"
#define YOUR_URL "YOUR_URL"
#define YOUR_DATABASE_SECRET_KEY "YOUR_DATABASE_SECRET_KEY"

//OpenWeather Data
#define YOUR_OPENWEATHER_API_KEY "YOUR_API_KEY"
#define YOUR_LATITUDE "YOUR_LAT_DATA"
#define YOUR_LONGITUDE "YOUR_LON_DATA"

#endif